apiVersion: v1
kind: ConfigMap
metadata:
  name: setters
  annotations:
    config.kubernetes.io/local-config: "true"
data:
  namespace: free5gc
  upf-n3-ip: 192.168.100.20
  upf-n3-subnet: "24"
  upf-n3-gateway: 192.168.100.1
  upf-n4-ip: 192.168.101.20
  upf-n4-subnet: "24"
  upf-n4-gateway: 192.168.101.1
  upf-n6-ip: 192.168.200.10
  upf-n6-subnet: "24"
  upf-n6-gateway: 192.168.200.1
  upf-nad-master: ens3
  ue-subnet: 10.1.0.0/16
  dnn: internet
  image-upf: free5gc/upf:v3.4.3
